// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyecdznqctlancbwbxfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5ZWNkem5xY3RsYW5jYndieGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODkzODgsImV4cCI6MjA2MTE2NTM4OH0.uXY7LeGNcOZRbCgVltrpO24ATlnKtddXjHL1Fe59GjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);